# Generated by Django 5.2 on 2025-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_customer_height_customer_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='malefemale', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
